language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "lts/*"
cache: npm
before_script: npm i -g nyc
script: nyc --reporter=lcov --reporter=text-lcov --exclude-after-remap=false npm test
after_success:
  - npm i -g codecov
  - codecov
